### ISSUE TITLE
How to prevent EVURLCache to cache a request with Cache-Control header?

### ISSUE THREAD

**Issue by CedricVanAsch** [evermeer/EVURLCache#30]
This question comes from someone on Stackoverflow, but we've been having the exact same issue. http://stackoverflow.com/questions/39020639/how-to-prevent-evurlcache-to-cache-a-request-with-cache-control-header

When I use EVURLCache, the POST request response for my AlamoFire request is also cached even if cache-control and Pragma headers are defined (should be cached only 4 hours in this case). 

It would be great if EVURLCache did actually cache for x hours, like the cache-control header defines, instead of just keeping the old cache.

**Comment by evermeer** [comment]
Hi, i'm on vacation and only have phone access to the internet.

EVURLCache is not so complex. There is full access to the request an
response parameters.

I'm back this monday and will have a look at it kater this week.

... Edwin

Op vrijdag 19 augustus 2016 heeft Cedric Van Asch <notifications@github.com>
het volgende geschreven:

**Comment by evermeer** [comment]
The enhancement for this was pushed to GitHub and CocoaPods as version 2.10.0

**Comment by wbervoets** [comment]
Hi,

Why does EVURLCache only look at the Access-Control-Max-Age request header to see if it needs to expire something? (eg Expire and Cache-Control header from response is not used)?

Thanks
Wim

**Comment by evermeer** [comment]
@wbervoets Until now I did not have a need to use anything else than the Access-Control-Max-Age. The response is handled in the storeCachedResponse function. As you can see I do react on the Cache-Control header. See the line:
`if let cacheControl = httpResponse.allHeaderFields["Cache-Control"] as? String {`
What else should I do there?
And what do you think I should do with the Expire header?

**Comment by wbervoets** [comment]
@evermeer when a Cache-Control headers specifies no-cache, EVURLCache will not cache the response. That's why I expected that a similar Cache-Control header like "Cache-Control: public, max-age=14400" would cache the item for 14400 seconds.

So when something is put in the cache, there could be optional expiration meta-data to be able to check if a cache item is expired when it is requested again.

----
I've been testing with adding Access-Control-Max-Age to the request and debugging cacheItemExpired.
I notice something strange with the cached item NSFileModificationDate being returned:

- request for URL is in the cache and NSFileModificationDate is eg 4 days ago
- new request for URL with Access-Control-Max-Age of 4hours. NSFileModificationDate returns 4 days ago and cacheItemExpired = true
(I presume the cache is then cleared, and a new item created for the same URL with NSFileModificationDate of today)
- new request for URL with Access-Control-Max-Age of 4hours. NSFileModificationDate is not today's date, but the same one from step 1)

=> the end result is that even if I do a request within 4 hours, the cache entry is not used.

It seems the NSFileModificationDate is not getting updated.

Wim
