### ISSUE TITLE
Support WKWebView?

### ISSUE THREAD

**Issue by caoyunxiao** [evermeer/EVURLCache#44]

**Comment by evermeer** [comment]
Sorry, WKWebView does not use the Cocoa stack with NSProtocol, NSUrl, NSUrlCache. When using WKWebView there is no alternative to do anything similar. (as far as I know)

For more info see for instance:
http://stackoverflow.com/questions/29573840/wkwebview-and-nsurlcache-to-serve-local-content

If you do want to use EVURLCashe (which is based on the NSUrlCache) Then you need to use the UIWebview

Closing this issue since WKWebView does not use NSUrlCache and therefore can never be supported by EVURLCache
