### ISSUE TITLE
Caching not working

### ISSUE THREAD

**Issue by francksyren** [evermeer/EVURLCache#51]
Hi,

I have noticed that the amount of data transferred over the network (in XCode network tab) is pretty much the same whether the cache is activated or not.
Since this is quite a vague sentence, I've created a small test project.

[CacheWebView.zip](https://github.com/evermeer/EVURLCache/files/1573365/CacheWebView.zip)

Here I see a difference of 600 kb when activated (3MB to 2.4MB) but I would assume everything should be cached (there is no data coming from a service).

The project is using Swift 4 and run with XCode 9.2 (iOS 11).

Thanks for your support
Franck

**Comment by evermeer** [comment]
Thanks for the demo app! that helps a lot!

It looks like there are 2 issues. You can find the files with an issue if you search the log for 'CACHE not found' the 2nd time you run the app.

Also if you run the app in the simulator, then you see the full path tasing by in the log. You could go to that folder to see what files are stored by EVURLCache. For instance the folder will be something like: /Users/eve21962/Library/Developer/CoreSimulator/Devices/EE77CF67-3637-4D37-B256-3D1C95A387F8/data/Containers/Data/Application/338F7A38-043B-4925-B6C8-ECE5234F03AE/Documents/Cache/www.sapfioritrial.com/

**1st issue**
There are url's where a unique ID is added to the end. If you look for instance at the url: www.sapfioritrial.com/core-fioritrialpublic-min.js__=1513758258636
then you see that the number is not added as a parameter, but it's added right after the .js
And because the number is new each time you start up the app, it will not be retrieved from the cache.

**2nd issue**
for some reason the storeCachedResponse function is not called for te requests for .xsodata. Strange enough it does call the cachedResponse function. But then again, isn't that a local storage? Then it would be strange that it tries to get it from the cache. I'm not sure how this should work.

**Comment by francksyren** [comment]
Thanks for your quick response.
When I look at the browser network tab, the request you mentioned is actually www.sapfioritrial.com/core-fioritrialpublic-min.js?_=1513758258636

I've looked into the folder and it looks like all my JS files are there, which is a good thing. But network traffic only goes from 3MB to 2.4MB which is a little surprising. When I do the same thing in the browser, it goes from 3MB to 175KB. 

Could it be some special headers not handled by the library?
