### ISSUE TITLE
Uppercase characters converted to lowercase

### ISSUE THREAD

**Issue by pukeanddie** [evermeer/EVURLCache#8]
Just noticed if I have 'PreCache/what.ever/js/JavaScript.js' files that are included as `<script src="js/JavaScript.js"></script>` in the html document  I'm still getting cache not found for 'PreCache/what.ever/js/javascript.js'. 

If I convert everything else to lowercase the problem goes away.

**Comment by evermeer** [comment]
Then you probably trying this on OS X are you? Because on iOS the HFS+ filesystem is used, HFS+ is not case-sensitive. It is, however, case-preserving. So on iOS casing should not matter how it's saved or retrieved.

I do see I use a .lowercaseString on line 158 of EVURLCache.swift. I think that one should go and I should preserver the casing. I will remove that one now. 

An alternative would be to convert everything everywhere to lowercase. Then you do have to be aware then the PreCache folder is populated it should be all in lowercase. I think I will make this an option of EVURLCache. I will have time to do that tomorrow. I will keep you posted

**Comment by evermeer** [comment]
I just published version 2.1.0. Could you try it out to see if this issue is fixed?
There is now a new property named FORCE_LOWERCASE which defaults to true.
This is a way to force a case insensitive url compare.

**Comment by evermeer** [comment]
Just let me know if you have any issues with this.
